## Deliverable 2. Create a Customer Travel Destinations Map.

In [2]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from Google_2_config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [3]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
0,0,Puerto Ayora,EC,-0.7393,-90.3518,66.54,88,67,4.00,broken clouds,09-18-2022 08:51:06
1,1,Korla,CN,41.7597,86.1469,83.97,11,100,7.31,overcast clouds,09-18-2022 08:51:07
2,2,Tiquicheo,MX,18.8833,-100.7333,71.49,98,100,1.83,overcast clouds,09-18-2022 08:50:39
3,3,Naze,JP,28.3667,129.4833,79.72,85,100,29.39,moderate rain,09-18-2022 08:51:07
4,4,Saint-Philippe,RE,-21.3585,55.7679,78.39,74,1,14.74,light rain,09-18-2022 08:51:08

In [4]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [6]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 95

In [7]:
# Filter the dataset to find the cities that fit the criteria.
sugested_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
sugested_cities_df.head(15)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
1,1,Korla,CN,41.7597,86.1469,83.97,11,100,7.31,overcast clouds,09-18-2022 08:51:07
3,3,Naze,JP,28.3667,129.4833,79.72,85,100,29.39,moderate rain,09-18-2022 08:51:07
4,4,Saint-Philippe,RE,-21.3585,55.7679,78.39,74,1,14.74,light rain,09-18-2022 08:51:08
6,6,Bengkulu,ID,-3.8004,102.2655,80.60,82,99,6.78,moderate rain,09-18-2022 08:51:09
12,12,Simga,IN,21.6333,81.7000,89.83,54,100,1.95,overcast clouds,09-18-2022 08:51:11
18,18,Wanning,CN,18.8003,110.3967,86.14,63,83,6.22,broken clouds,09-18-2022 08:51:14
26,26,Jijiga,ET,9.3500,42.8000,77.92,43,56,8.48,broken clouds,09-18-2022 08:51:17
29,29,Butaritari,KI,3.0707,172.7902,82.26,77,7,13.31,light rain,09-18-2022 08:51:19
31,31,Port-Gentil,GA,-0.7193,8.7815,80.56,74,75,16.11,broken clouds,09-18-2022 08:51:19
36,36,Kutum,SD,14.2000,24.6667,82.42,41,94,6.06,overcast clouds,09-18-2022 08:51:21
39,39,Wajir,KE,1.7471,40.0573,85.96,42,40,9.22,scattered clouds,09-18-2022 08:51:22
50,50,Katsuura,JP,35.1333,140.3000,80.62,91,100,18.70,moderate rain,09-18-2022 08:51:27
51,51,Abu Samrah,SY,35.3029,37.1841,92.68,11,0,9.42,clear sky,09-18-2022 08:51:27
55,55,Port Moresby,PG,-9.4431,147.1797,85.42,74,20,8.05,haze,09-18-2022 08:51:28
56,56,Hithadhoo,MV,-0.6000,73.0833,82.53,71,15,7.38,few clouds,09-18-2022 08:46:53

In [8]:
# 4a. Determine if there are any empty rows.
sugested_cities_df.notnull().sum()

City_ID                266
City                   266
Country                262
Lat                    266
Lng                    266
Max Temp               266
Humidity               266
Cloudiness             266
Wind Speed             266
Current Description    266
Date                   266
dtype: int64

In [9]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
sugested_cities_df.dropna()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
1,1,Korla,CN,41.7597,86.1469,83.97,11,100,7.31,overcast clouds,09-18-2022 08:51:07
3,3,Naze,JP,28.3667,129.4833,79.72,85,100,29.39,moderate rain,09-18-2022 08:51:07
4,4,Saint-Philippe,RE,-21.3585,55.7679,78.39,74,1,14.74,light rain,09-18-2022 08:51:08
6,6,Bengkulu,ID,-3.8004,102.2655,80.60,82,99,6.78,moderate rain,09-18-2022 08:51:09
12,12,Simga,IN,21.6333,81.7000,89.83,54,100,1.95,overcast clouds,09-18-2022 08:51:11
...,...,...,...,...,...,...,...,...,...,...,...
675,675,Lamu,KE,-2.2717,40.9020,80.51,71,26,15.55,scattered clouds,09-18-2022 08:55:40
677,677,Mlonggo,ID,-6.5333,110.7000,88.32,54,60,12.12,broken clouds,09-18-2022 08:55:41
679,679,Lengshuijiang,CN,27.6881,111.4294,94.35,37,70,7.47,broken clouds,09-18-2022 08:55:42
682,682,Jian,CN,27.1172,114.9793,84.31,48,96,3.24,overcast clouds,09-18-2022 08:55:43
685,685,Lhokseumawe,ID,5.1801,97.1507,82.62,77,78,7.27,broken clouds,09-18-2022 08:55:44

In [10]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = sugested_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(15)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Korla,CN,83.97,overcast clouds,41.7597,86.1469,
3,Naze,JP,79.72,moderate rain,28.3667,129.4833,
4,Saint-Philippe,RE,78.39,light rain,-21.3585,55.7679,
6,Bengkulu,ID,80.60,moderate rain,-3.8004,102.2655,
12,Simga,IN,89.83,overcast clouds,21.6333,81.7000,
18,Wanning,CN,86.14,broken clouds,18.8003,110.3967,
26,Jijiga,ET,77.92,broken clouds,9.3500,42.8000,
29,Butaritari,KI,82.26,light rain,3.0707,172.7902,
31,Port-Gentil,GA,80.56,broken clouds,-0.7193,8.7815,
36,Kutum,SD,82.42,overcast clouds,14.2000,24.6667,
39,Wajir,KE,85.96,scattered clouds,1.7471,40.0573,
50,Katsuura,JP,80.62,moderate rain,35.1333,140.3000,
51,Abu Samrah,SY,92.68,clear sky,35.3029,37.1841,
55,Port Moresby,PG,85.42,haze,-9.4431,147.1797,
56,Hithadhoo,MV,82.53,few clouds,-0.6000,73.0833,

In [11]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [12]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna(axis="index", how="any")
clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Korla,CN,83.97,overcast clouds,41.7597,86.1469,Gulisitan Hotel
3,Naze,JP,79.72,moderate rain,28.3667,129.4833,Shishime Hotel
4,Saint-Philippe,RE,78.39,light rain,-21.3585,55.7679,Le four à pain
6,Bengkulu,ID,80.60,moderate rain,-3.8004,102.2655,Grage Hotel Bengkulu
12,Simga,IN,89.83,overcast clouds,21.6333,81.7000,OM Hotel & Sweet
18,Wanning,CN,86.14,broken clouds,18.8003,110.3967,Paradise Hotel
26,Jijiga,ET,77.92,broken clouds,9.3500,42.8000,RAMAAS HOTEL
29,Butaritari,KI,82.26,light rain,3.0707,172.7902,Isles Sunset Lodge
31,Port-Gentil,GA,80.56,broken clouds,-0.7193,8.7815,Fengshui Residence
36,Kutum,SD,82.42,overcast clouds,14.2000,24.6667,Dibbo areaمنطقة دبو

In [14]:
# 8a. Create the output File (CSV)
output_data_file = "../Vacation_Search/WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
sugested_cities_df.to_csv(output_data_file, index_label="City_ID")

In [15]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [16]:
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))